
export const LOADING = 'LOADING';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const CORREO_ERROR = 'CORREO_ERROR';
export const RESET_URL_OK = 'RESET_URL_OK'
export const RESET_URL_ERROR = 'RESET_URL_ERROR'
export const RESTABLECER_OK = 'RESTABLECER_OK'
export const RESTABLECER_ERROR = 'RESTABLECER_ERROR'

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO'
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR'

export const CREAR_ENLACE_EXITO = 'CREAR_ARCHIVO_EXITO'
export const CREAR_ENLACE_ERROR = 'CREAR_ARCHIVO_ERROR'

export const DATOS_ARCHIVO = 'DATOS_ARCHIVO'

export const LIMPIAR_STATE = 'LIMPIAR_STATE';

export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD'
export const AGREGAR_DESCARGAS = 'AGREGAR_DESCARGAS'

export const LISTA_LINKS = 'LISTA_LINKS';
export const LISTA_LINKS_ACTUALIZADA = 'LISTA_LINKS_ACTUALIZADA'


